#pragma once
enum class_ids
{
    CAI_BaseNPC = 0 ,
    CAK47 ,
    CBaseAnimating ,
    CBaseAnimatingOverlay ,
    CBaseAttributableItem ,
    CBaseButton ,
    CBaseCombatCharacter ,
    CBaseCombatWeapon ,
    CBaseCSGrenade ,
    CBaseCSGrenadeProjectile ,
    CBaseDoor ,
    CBaseEntity ,
    CBaseFlex ,
    CBaseGrenade ,
    CBaseParticleEntity ,
    CBasePlayer ,
    CBasePropDoor ,
    CBaseTeamObjectiveResource ,
    CBaseTempEntity ,
    CBaseToggle ,
    CBaseTrigger ,
    CBaseViewModel ,
    CBaseVPhysicsTrigger ,
    CBaseWeaponWorldModel ,
    CBeam ,
    CBeamSpotlight ,
    CBoneFollower ,
    CBRC4Target ,
    CBreachCharge ,
    CBreachChargeProjectile ,
    CBreakableProp ,
    CBreakableSurface ,
    CC4 ,
    CCascadeLight ,
    CChicken ,
    CColorCorrection ,
    CColorCorrectionVolume ,
    CCSGameRulesProxy ,
    CCSPlayer ,
    CCSPlayerResource ,
    CCSRagdoll ,
    CCSTeam ,
    CDangerZone ,
    CDangerZoneController ,
    CDEagle ,
    CDecoyGrenade ,
    CDecoyProjectile ,
    CDrone ,
    CDronegun ,
    CDynamicLight ,
    CDynamicProp ,
    CEconEntity ,
    CEconWearable ,
    CEmbers ,
    CEntityDissolve ,
    CEntityFlame ,
    CEntityFreezing ,
    CEntityParticleTrail ,
    CEnvAmbientLight ,
    CEnvDetailController ,
    CEnvDOFController ,
    CEnvGasCanister ,
    CEnvParticleScript ,
    CEnvProjectedTexture ,
    CEnvQuadraticBeam ,
    CEnvScreenEffect ,
    CEnvScreenOverlay ,
    CEnvTonemapController ,
    CEnvWind ,
    CFEPlayerDecal ,
    CFireCrackerBlast ,
    CFireSmoke ,
    CFireTrail ,
    CFish ,
    CFists ,
    CFlashbang ,
    CFogController ,
    CFootstepControl ,
    CFunc_Dust ,
    CFunc_LOD ,
    CFuncAreaPortalWindow ,
    CFuncBrush ,
    CFuncConveyor ,
    CFuncLadder ,
    CFuncMonitor ,
    CFuncMoveLinear ,
    CFuncOccluder ,
    CFuncReflectiveGlass ,
    CFuncRotating ,
    CFuncSmokeVolume ,
    CFuncTrackTrain ,
    CGameRulesProxy ,
    CGrassBurn ,
    CHandleTest ,
    CHEGrenade ,
    CHostage ,
    CHostageCarriableProp ,
    CIncendiaryGrenade ,
    CInferno ,
    CInfoLadderDismount ,
    CInfoMapRegion ,
    CInfoOverlayAccessor ,
    CItem_Healthshot ,
    CItemCash ,
    CItemDogtags ,
    CKnife ,
    CKnifeGG ,
    CLightGlow ,
    CMaterialModifyControl ,
    CMelee ,
    CMolotovGrenade ,
    CMolotovProjectile ,
    CMovieDisplay ,
    CParadropChopper ,
    CParticleFire ,
    CParticlePerformanceMonitor ,
    CParticleSystem ,
    CPhysBox ,
    CPhysBoxMultiplayer ,
    CPhysicsProp ,
    CPhysicsPropMultiplayer ,
    CPhysMagnet ,
    CPhysPropAmmoBox ,
    CPhysPropLootCrate ,
    CPhysPropRadarJammer ,
    CPhysPropWeaponUpgrade ,
    CPlantedC4 ,
    CPlasma ,
    CPlayerResource ,
    CPointCamera ,
    CPointCommentaryNode ,
    CPointWorldText ,
    CPoseController ,
    CPostProcessController ,
    CPrecipitation ,
    CPrecipitationBlocker ,
    CPredictedViewModel ,
    CProp_Hallucination ,
    CPropCounter ,
    CPropDoorRotating ,
    CPropJeep ,
    CPropVehicleDriveable ,
    CRagdollManager ,
    CRagdollProp ,
    CRagdollPropAttached ,
    CRopeKeyframe ,
    CSCAR17 ,
    CSceneEntity ,
    CSensorGrenade ,
    CSensorGrenadeProjectile ,
    CShadowControl ,
    CSlideshowDisplay ,
    CSmokeGrenade ,
    CSmokeGrenadeProjectile ,
    CSmokeStack ,
    CSpatialEntity ,
    CSpotlightEnd ,
    CSprite ,
    CSpriteOriented ,
    CSpriteTrail ,
    CStatueProp ,
    CSteamJet ,
    CSun ,
    CSunlightShadowControl ,
    CSurvivalSpawnChopper ,
    CTablet ,
    CTeam ,
    CTeamplayRoundBasedRulesProxy ,
    CTEArmorRicochet ,
    CTEBaseBeam ,
    CTEBeamEntPoint ,
    CTEBeamEnts ,
    CTEBeamFollow ,
    CTEBeamLaser ,
    CTEBeamPoints ,
    CTEBeamRing ,
    CTEBeamRingPoint ,
    CTEBeamSpline ,
    CTEBloodSprite ,
    CTEBloodStream ,
    CTEBreakModel ,
    CTEBSPDecal ,
    CTEBubbles ,
    CTEBubbleTrail ,
    CTEClientProjectile ,
    CTEDecal ,
    CTEDust ,
    CTEDynamicLight ,
    CTEEffectDispatch ,
    CTEEnergySplash ,
    CTEExplosion ,
    CTEFireBullets ,
    CTEFizz ,
    CTEFootprintDecal ,
    CTEFoundryHelpers ,
    CTEGaussExplosion ,
    CTEGlowSprite ,
    CTEImpact ,
    CTEKillPlayerAttachments ,
    CTELargeFunnel ,
    CTEMetalSparks ,
    CTEMuzzleFlash ,
    CTEParticleSystem ,
    CTEPhysicsProp ,
    CTEPlantBomb ,
    CTEPlayerAnimEvent ,
    CTEPlayerDecal ,
    CTEProjectedDecal ,
    CTERadioIcon ,
    CTEShatterSurface ,
    CTEShowLine ,
    CTesla ,
    CTESmoke ,
    CTESparks ,
    CTESprite ,
    CTESpriteSpray ,
    CTest_ProxyToggle_Networkable ,
    CTestTraceline ,
    CTEWorldDecal ,
    CTriggerPlayerMovement ,
    CTriggerSoundOperator ,
    CVGuiScreen ,
    CVoteController ,
    CWaterBullet ,
    CWaterLODControl ,
    CWeaponAug ,
    CWeaponAWP ,
    CWeaponBaseItem ,
    CWeaponBizon ,
    CWeaponCSBase ,
    CWeaponCSBaseGun ,
    CWeaponCycler ,
    CWeaponElite ,
    CWeaponFamas ,
    CWeaponFiveSeven ,
    CWeaponG3SG1 ,
    CWeaponGalil ,
    CWeaponGalilAR ,
    CWeaponGlock ,
    CWeaponHKP2000 ,
    CWeaponM249 ,
    CWeaponM3 ,
    CWeaponM4A1 ,
    CWeaponMAC10 ,
    CWeaponMag7 ,
    CWeaponMP5Navy ,
    CWeaponMP7 ,
    CWeaponMP9 ,
    CWeaponNegev ,
    CWeaponNOVA ,
    CWeaponP228 ,
    CWeaponP250 ,
    CWeaponP90 ,
    CWeaponSawedoff ,
    CWeaponSCAR20 ,
    CWeaponScout ,
    CWeaponSG550 ,
    CWeaponSG552 ,
    CWeaponSG556 ,
    CWeaponSSG08 ,
    CWeaponTaser ,
    CWeaponTec9 ,
    CWeaponTMP ,
    CWeaponUMP45 ,
    CWeaponUSP ,
    CWeaponXM1014 ,
    CWorld ,
    CWorldVguiText ,
    DustTrail ,
    MovieExplosion ,
    ParticleSmokeGrenade ,
    RocketTrail ,
    SmokeTrail ,
    SporeExplosion ,
    SporeTrail
};

enum move_type : uint8_t
{
    MOVETYPE_NONE = 0 ,
    MOVETYPE_ISOMETRIC ,
    MOVETYPE_WALK ,
    MOVETYPE_STEP ,
    MOVETYPE_FLY ,
    MOVETYPE_FLYGRAVITY ,
    MOVETYPE_VPHYSICS ,
    MOVETYPE_PUSH ,
    MOVETYPE_NOCLIP ,
    MOVETYPE_LADDER ,
    MOVETYPE_OBSERVER ,
    MOVETYPE_CUSTOM ,
    MOVETYPE_LAST = MOVETYPE_CUSTOM ,
    MOVETYPE_MAX_BITS = 4
};

enum weapon_type : int
{
    WEAPONTYPE_KNIFE = 0 ,
    WEAPONTYPE_PISTOL ,
    WEAPONTYPE_SUBMACHINEGUN ,
    WEAPONTYPE_RIFLE ,
    WEAPONTYPE_SHOTGUN ,
    WEAPONTYPE_SNIPER_RIFLE ,
    WEAPONTYPE_MACHINEGUN ,
    WEAPONTYPE_C4 ,
};

enum weapon_ids
{
    WEAPON_NONE = 0 ,
    WEAPON_DEAGLE ,
    WEAPON_ELITE ,
    WEAPON_FIVESEVEN ,
    WEAPON_GLOCK ,
    WEAPON_AK47 = 7 ,
    WEAPON_AUG ,
    WEAPON_AWP ,
    WEAPON_FAMAS ,
    WEAPON_G3SG1 ,
    WEAPON_GALILAR = 13 ,
    WEAPON_M249 ,
    WEAPON_M4A1 = 16 ,
    WEAPON_MAC10 ,
    WEAPON_P90 = 19 ,
    WEAPON_MP5SD = 23 ,
    WEAPON_UMP45 ,
    WEAPON_XM1014 ,
    WEAPON_BIZON ,
    WEAPON_MAG7 ,
    WEAPON_NEGEV ,
    WEAPON_SAWEDOFF ,
    WEAPON_TEC9 ,
    WEAPON_TASER ,
    WEAPON_HKP2000 ,
    WEAPON_MP7 ,
    WEAPON_MP9 ,
    WEAPON_NOVA ,
    WEAPON_P250 ,
    WEAPON_SCAR20 = 38 ,
    WEAPON_SG558 ,
    WEAPON_SSG08 ,
    WEAPON_KNIFEGG ,
    WEAPON_KNIFE ,
    WEAPON_FLASHBANG ,
    WEAPON_HEGRENADE ,
    WEAPON_SMOKEGRENADE ,
    WEAPON_MOLOTOV ,
    WEAPON_DECOY ,
    WEAPON_INCGRENADE ,
    WEAPON_C4 ,
    WEAPON_HEALTHSHOT = 57 ,
    WEAPON_KNIFE_T = 59 ,
    WEAPON_M4A1_SILENCER ,
    WEAPON_USP_SILENCER ,
    WEAPON_CZ75A = 63 ,
    WEAPON_REVOLVER ,
    WEAPON_TAGRENADE = 68 ,
    WEAPON_FISTS ,
    WEAPON_BREACHCHARGE ,
    WEAPON_TABLET = 72 ,
    WEAPON_MELEE = 74 ,
    WEAPON_AXE ,
    WEAPON_HAMMER ,
    WEAPON_SPANNER = 78 ,
    WEAPON_KNIFE_GHOST = 80 ,
    WEAPON_FIREBOMB ,
    WEAPON_DIVERSION ,
    WEAPON_FRAG_GRENADE ,
    WEAPON_KNIFE_BAYONET = 500 ,
    WEAPON_KNIFE_FLIP = 505 ,
    WEAPON_KNIFE_GUT ,
    WEAPON_KNIFE_KARAMBIT ,
    WEAPON_KNIFE_M9_BAYONET ,
    WEAPON_KNIFE_TACTICAL ,
    WEAPON_KNIFE_FALCHION = 512 ,
    WEAPON_KNIFE_SURVIVAL_BOWIE = 514 ,
    WEAPON_KNIFE_BUTTERFLY ,
    WEAPON_KNIFE_PUSH ,
    WEAPON_KNIFE_URSUS = 519 ,
    WEAPON_KNIFE_GYPSY_JACKKNIFE ,
    WEAPON_KNIFE_STILETTO = 522 ,
    WEAPON_KNIFE_WIDOWMAKER ,
    GLOVE_STUDDED_BLOODHOUND = 5027 ,
    GLOVE_T_SIDE = 5028 ,
    GLOVE_CT_SIDE = 5029 ,
    GLOVE_SPORTY = 5030 ,
    GLOVE_SLICK = 5031 ,
    GLOVE_LEATHER_WRAP = 5032 ,
    GLOVE_MOTORCYCLE = 5033 ,
    GLOVE_SPECIALIST = 5034
};

enum cmd_buttons_code
{
    IN_ATTACK = ( 1 << 0 ) ,
    IN_JUMP = ( 1 << 1 ) ,
    IN_DUCK = ( 1 << 2 ) ,
    IN_FORWARD = ( 1 << 3 ) ,
    IN_BACK = ( 1 << 4 ) ,
    IN_USE = ( 1 << 5 ) ,
    IN_CANCEL = ( 1 << 6 ) ,
    IN_LEFT = ( 1 << 7 ) ,
    IN_RIGHT = ( 1 << 8 ) ,
    IN_MOVELEFT = ( 1 << 9 ) ,
    IN_MOVERIGHT = ( 1 << 10 ) ,
    IN_ATTACK2 = ( 1 << 11 ) ,
    IN_RUN = ( 1 << 12 ) ,
    IN_RELOAD = ( 1 << 13 ) ,
    IN_ALT1 = ( 1 << 14 ) ,
    IN_ALT2 = ( 1 << 15 ) ,
    IN_SCORE = ( 1 << 16 ) ,
    IN_SPEED = ( 1 << 17 ) ,
    IN_WALK = ( 1 << 18 ) ,
    IN_ZOOM = ( 1 << 19 ) ,
    IN_WEAPON1 = ( 1 << 20 ) ,
    IN_WEAPON2 = ( 1 << 21 ) ,
    IN_BULLRUSH = ( 1 << 22 ) ,
    IN_GRENADE1 = ( 1 << 23 ) ,
    IN_GRENADE2 = ( 1 << 24 ) ,
    IN_ATTACK3 = ( 1 << 25 ) ,
};

enum hit_groups
{
    HITGROUP_INVALID = -1 ,
    HITGROUP_GENERIC ,
    HITGROUP_HEAD ,
    HITGROUP_CHEST ,
    HITGROUP_STOMACH ,
    HITGROUP_LEFTARM ,
    HITGROUP_RIGHTARM ,
    HITGROUP_LEFTLEG ,
    HITGROUP_RIGHTLEG ,
    HITGROUP_GEAR = 10
};
